import { Err, Ok, Result } from 'oxide.ts';
import * as fs from 'fs';
import * as path from 'path';
import { AssemblyDescriptor, AssemblyPathLocation } from './IBackendParametersOutlook';
import { BackendVariantOutlook15Plus } from './BackendVariantOutlook15Plus';

/**
 * Structure for the deps.json file used by CoreCLR to resolve assemblies.
 */
export interface DepsJsonStructure {
  runtimeTarget: {
    name: string;
    signature: string;
  };
  compilationOptions: Record<string, unknown>;
  targets: {
    [key: string]: {
      [key: string]: {
        dependencies?: Record<string, string>;
        runtime?: Record<
          string,
          { assemblyVersion?: string; fileVersion?: string } | Record<string, never>
        >;
      };
    };
  };
  libraries: {
    [key: string]: {
      type: string;
      serviceable: boolean;
      sha512?: string;
      path?: string;
      hashPath?: string;
    };
  };
}

/**
 * Structure for the runtimeconfig.json file used by CoreCLR.
 */
export interface RuntimeConfigStructure {
  runtimeOptions: {
    tfm?: string;
    framework?: {
      name: string;
      version: string;
    };
    additionalProbingPaths?: string[];
    configProperties?: Record<string, unknown>;
  };
}

/**
 * Generates the OutlookComBridge.deps.json and OutlookComBridge.runtimeconfig.json files
 * for CoreCLR assembly resolution.
 *
 * CoreCLR cannot load assemblies from the GAC like .NET Framework does.
 * Instead, it uses the deps.json file to resolve dependencies at runtime.
 * This generator loads a template deps.json (generated by dotnet build) and
 * modifies it based on the selected backend variant's assembly descriptors.
 *
 * The deps.json format for GAC assemblies requires:
 * - Target/library keys in format: `<package_name>/<version>__<public_key_token>`
 * - Library path in lowercase format matching GAC folder structure
 * - Runtime entry with just the DLL filename
 *
 * The runtimeconfig.json must include additionalProbingPaths:
 * - The bin path (for local assemblies like EdgeJs.dll)
 * - GAC_MSIL path (for Office interop assemblies)
 * - .NET shared framework path (for runtime assemblies)
 */
// TODO: Create Unit tests for this class
export class BackendOutlookDepsJsonGenerator {
  private readonly binPath: string;
  private readonly templatePath: string;
  private readonly depsJsonFilePath: string;
  private readonly depsJsonTemplateFilePath: string;
  private readonly runtimeConfigFilePath: string;
  private readonly runtimeConfigTemplateFilePath: string;
  private readonly assemblyDescriptors: AssemblyDescriptor[];
  private readonly dotnetPath: string;

  /**
   * Creates a new BackendOutlookDepsJsonGenerator.
   *
   * @param binPath The output directory for generated files
   * @param templatePath The directory containing template files
   * @param depsJsonPathFileName The filename for the deps.json file
   * @param runtimeConfigFileName The filename for the runtimeconfig.json file
   * @param assemblyDescriptors Array of all assembly descriptors to include (EdgeJs, Office, Outlook, etc.)
   * @param dotnetPath Path to the .NET runtime installation directory
   */
  constructor(
    binPath: string,
    templatePath: string,
    depsJsonPathFileName: string,
    runtimeConfigFileName: string,
    assemblyDescriptors: AssemblyDescriptor[],
    dotnetPath: string
  ) {
    this.binPath = binPath;
    this.templatePath = templatePath;
    this.depsJsonFilePath = this.binPath + path.sep + depsJsonPathFileName;
    this.depsJsonTemplateFilePath = this.templatePath + path.sep + depsJsonPathFileName;
    this.runtimeConfigFilePath = this.binPath + path.sep + runtimeConfigFileName;
    this.runtimeConfigTemplateFilePath = this.templatePath + path.sep + runtimeConfigFileName;
    this.assemblyDescriptors = assemblyDescriptors;
    this.dotnetPath = dotnetPath;
  }

  /**
   * Generates the OutlookComBridge.deps.json file based on the assembly descriptors.
   * Loads the template file and modifies it with the assembly versions.
   *
   * @returns Result indicating success or error message
   */
  public generate(): Result<void, string> {
    // Load template file
    let depsJson: DepsJsonStructure;
    try {
      const templateContent = fs.readFileSync(this.depsJsonTemplateFilePath, 'utf8');
      depsJson = JSON.parse(templateContent) as DepsJsonStructure;
    } catch (error) {
      const errorMessage = `Failed to read template deps.json: ${error instanceof Error ? error.message : String(error)}`;
      console.error(errorMessage);
      return Err(errorMessage);
    }

    // Modify the in-memory structure with assembly descriptors
    const modifyResult = this.modifyDepsJson(depsJson, this.assemblyDescriptors);
    if (modifyResult.isErr()) {
      return modifyResult;
    }

    try {
      const depsJsonContent = JSON.stringify(modifyResult.unwrap(), null, 2);
      fs.writeFileSync(this.depsJsonFilePath, depsJsonContent, 'utf8');
      console.log(`Successfully generated deps.json at ${this.depsJsonFilePath}`);
    } catch (error) {
      const errorMessage = `Failed to write deps.json: ${error instanceof Error ? error.message : String(error)}`;
      console.error(errorMessage);
      return Err(errorMessage);
    }

    // Generate runtimeconfig.json with additionalProbingPaths
    const runtimeConfigResult = this.generateRuntimeConfig(this.assemblyDescriptors);
    if (runtimeConfigResult.isErr()) {
      return runtimeConfigResult;
    }

    return Ok(undefined);
  }

  /**
   * Generates the runtimeconfig.json file with additionalProbingPaths for assembly resolution.
   *
   * CoreCLR uses these probing paths to locate assemblies at runtime:
   * - binPath: For local assemblies (EdgeJs.dll, Microsoft.Extensions.DependencyModel.dll, etc.)
   * - GAC_MSIL: For Office interop assemblies installed with Microsoft Office
   * - .NET shared framework: For .NET runtime assemblies
   *
   * @param assemblyDescriptors Array of assembly descriptors (reserved for future use)
   */
  private generateRuntimeConfig(assemblyDescriptors: AssemblyDescriptor[]): Result<void, string> {
    // Load template file
    let runtimeConfig: RuntimeConfigStructure;
    try {
      const templateContent = fs.readFileSync(this.runtimeConfigTemplateFilePath, 'utf8');
      runtimeConfig = JSON.parse(templateContent) as RuntimeConfigStructure;
    } catch (error) {
      const errorMessage = `Failed to read template runtimeconfig.json: ${error instanceof Error ? error.message : String(error)}`;
      console.error(errorMessage);
      return Err(errorMessage);
    }

    // Build probing paths in order of priority
    const probingPaths: string[] = [];

    // 1. Add the bin path itself as a probing path (for EdgeJs.dll, local DLLs)
    probingPaths.push(path.resolve(this.binPath));

    // 2. Add GAC_MSIL path for Office interop assemblies
    probingPaths.push(BackendVariantOutlook15Plus.GAC_MSIL_PATH);

    // 3. Add .NET shared framework path for runtime assemblies
    const sharedFrameworkPath = this.detectSharedFrameworkPath();
    if (sharedFrameworkPath) {
      probingPaths.push(sharedFrameworkPath);
    } else {
      console.warn(
        'Could not detect .NET shared framework path, CoreCLR may not resolve all assemblies'
      );
    }

    // Set additionalProbingPaths in the runtimeconfig
    runtimeConfig.runtimeOptions.additionalProbingPaths = probingPaths;

    try {
      const runtimeConfigContent = JSON.stringify(runtimeConfig, null, 2);
      fs.writeFileSync(this.runtimeConfigFilePath, runtimeConfigContent, 'utf8');
      console.log(`Successfully generated runtimeconfig.json at ${this.runtimeConfigFilePath}`);
      console.log(`  additionalProbingPaths: ${probingPaths.join(', ')}`);
      return Ok(undefined);
    } catch (error) {
      const errorMessage = `Failed to write runtimeconfig.json: ${error instanceof Error ? error.message : String(error)}`;
      console.error(errorMessage);
      return Err(errorMessage);
    }
  }

  /**
   * Detects the .NET shared framework path based on the configured dotnetPath.
   * Looks for the latest installed .NET 8.x runtime.
   *
   * @returns The path to the shared framework or null if not found
   */
  private detectSharedFrameworkPath(): string | null {
    const sharedFrameworkBase = path.join(this.dotnetPath, 'shared', 'Microsoft.NETCore.App');

    if (!fs.existsSync(sharedFrameworkBase)) {
      console.warn(`Shared framework directory not found: ${sharedFrameworkBase}`);
      return null;
    }

    try {
      // Get all version directories
      const versions = fs
        .readdirSync(sharedFrameworkBase)
        .filter((v) => v.startsWith('8.')) // Filter for .NET 8.x
        .sort((a, b) => {
          // Sort by version number (8.0.1, 8.0.22, etc.)
          const partsA = a.split('.').map(Number);
          const partsB = b.split('.').map(Number);
          for (let i = 0; i < Math.max(partsA.length, partsB.length); i++) {
            const numA = partsA[i] || 0;
            const numB = partsB[i] || 0;
            if (numA !== numB) return numB - numA; // Descending order
          }
          return 0;
        });

      if (versions.length > 0) {
        const latestVersion = versions[0];
        const frameworkPath = path.join(sharedFrameworkBase, latestVersion);
        console.log(`Detected .NET shared framework: ${frameworkPath}`);
        return frameworkPath;
      }

      console.warn(`No .NET 8.x versions found in: ${sharedFrameworkBase}`);
      return null;
    } catch (error) {
      console.warn(`Failed to detect shared framework: ${error}`);
      return null;
    }
  }

  /**
   * Modifies the deps.json structure with the provided assembly versions.
   * Updates both the targets and libraries sections.
   *
   * For GAC assemblies, the key format must be:
   * `<package_name>/<version>__<public_key_token>`
   *
   * The library path must match the GAC folder structure:
   * `<package_name>/<version>__<public_key_token>`
   *
   * @param depsJson The deps.json structure to modify
   * @param assemblyDescriptors Array of assembly descriptors to add/update
   */
  private modifyDepsJson(
    depsJson: DepsJsonStructure,
    assemblyDescriptors: AssemblyDescriptor[]
  ): Result<DepsJsonStructure, string> {
    let modifiedDepsJson = depsJson;
    const runtimeTarget = modifiedDepsJson.runtimeTarget.name;
    const targetSection = modifiedDepsJson.targets[runtimeTarget];

    if (!targetSection) {
      return Err(`Runtime target '${runtimeTarget}' not found in template`);
    }

    // Find and update the main project's dependencies with the versioned keys
    const mainProjectKey = Object.keys(targetSection).find((key) =>
      key.startsWith('OutlookComBridge/')
    );
    if (mainProjectKey && targetSection[mainProjectKey]?.dependencies) {
      // Process each assembly descriptor
      for (const descriptor of assemblyDescriptors) {
        // Remove old dependency key if it exists
        delete targetSection[mainProjectKey].dependencies[descriptor.name];

        // Add new dependency with versioned key matching the target entry
        const newDepKey = this.buildDebsEntryName(descriptor);
        targetSection[mainProjectKey].dependencies[newDepKey] =
          this.buildDebsVersionRef(descriptor);
      }
    }

    // Update targets and libraries sections for each descriptor
    for (const descriptor of assemblyDescriptors) {
      this.addAssemblyEntry(targetSection, modifiedDepsJson.libraries, descriptor);
    }

    // Normalize NuGet package paths to flat structure
    // NuGet packages are copied flat to the bin folder, so we need to update
    // runtime paths from "lib/net5.0/Assembly.dll" to just "Assembly.dll".
    // Plugin-type assemblies keep their relative paths (e.g., "bin/Release/EdgeJs.dll").
    this.normalizeNuGetPackagePaths(targetSection, modifiedDepsJson.libraries, assemblyDescriptors);

    return Ok(modifiedDepsJson);
  }

  /**
   * Normalizes NuGet package runtime paths to flat structure.
   *
   * When NuGet packages are copied flat to the deployment folder (not in their
   * original NuGet package structure), the deps.json runtime paths need to be
   * updated from paths like "lib/net5.0/Google.Protobuf.dll" to just "Google.Protobuf.dll".
   *
   * This also clears the library path so CoreCLR looks for the assembly directly
   * in the probing paths rather than in a package subfolder.
   *
   * Plugin-type assemblies are excluded from normalization as they use explicit
   * relative paths (e.g., "bin/Release/EdgeJs.dll").
   *
   * @param targetSection The targets section of the deps.json
   * @param libraries The libraries section of the deps.json
   * @param assemblyDescriptors Array of assembly descriptors to check for Plugin type
   */
  private normalizeNuGetPackagePaths(
    targetSection: DepsJsonStructure['targets'][string],
    libraries: DepsJsonStructure['libraries'],
    assemblyDescriptors: AssemblyDescriptor[]
  ): void {
    // Build a set of entry keys for Plugin-type assemblies (should not be normalized)
    const pluginEntryKeys = new Set(
      assemblyDescriptors
        .filter((d) => d.pathLocationType === AssemblyPathLocation.Plugin)
        .map((d) => this.buildDebsEntryName(d))
    );

    for (const [entryKey, entry] of Object.entries(targetSection)) {
      // Skip main project entry
      if (entryKey.startsWith('OutlookComBridge/')) {
        continue;
      }

      // Skip Plugin-type assemblies - they use explicit relative paths
      if (pluginEntryKeys.has(entryKey)) {
        continue;
      }

      // Normalize runtime paths
      if (entry.runtime) {
        const newRuntime: Record<
          string,
          { assemblyVersion?: string; fileVersion?: string } | Record<string, never>
        > = {};
        for (const [runtimePath, runtimeValue] of Object.entries(entry.runtime)) {
          // Extract just the filename from paths like "lib/net5.0/Google.Protobuf.dll"
          const fileName = path.basename(runtimePath);
          newRuntime[fileName] = runtimeValue;
        }
        entry.runtime = newRuntime;
      }
    }

    // Clear library paths so CoreCLR uses probing paths directly
    for (const [libraryKey, library] of Object.entries(libraries)) {
      // Skip main project entry
      if (libraryKey.startsWith('OutlookComBridge/')) {
        continue;
      }
      // Clear path so assembly is found directly in probing paths
      if (library.path) {
        library.path = '';
      }
    }
  }

  /**
   * Builds the key format used for assembly entries depending on path location type.
   */
  private buildDebsEntryName(descriptor: AssemblyDescriptor): string {
    switch (descriptor.pathLocationType) {
      case AssemblyPathLocation.Absolute:
        return `${descriptor.path}`;
      case AssemblyPathLocation.Plugin:
        return `${descriptor.path}`;
      case AssemblyPathLocation.GAC:
        return (
          `${descriptor.path}/${descriptor.assemblyVersion}` +
          (descriptor.publicKeyToken ? `__${descriptor.publicKeyToken}` : '')
        );
      default:
        // Programming error: should never reach here
        throw new Error(`Unsupported AssemblyPathLocation: ${descriptor.pathLocationType}`);
    }
  }

  /**
   * Builds the version reference used for assembly entries depending on path location type.
   */
  private buildDebsVersionRef(descriptor: AssemblyDescriptor): string {
    switch (descriptor.pathLocationType) {
      case AssemblyPathLocation.Absolute:
        return '';
      case AssemblyPathLocation.Plugin:
        return descriptor.assemblyVersion?.split('.').slice(0, 3).join('.') || '';
      case AssemblyPathLocation.GAC:
        return (
          `${descriptor.assemblyVersion}` +
          (descriptor.publicKeyToken ? `__${descriptor.publicKeyToken}` : '')
        );
      default:
        // Programming error: should never reach here
        throw new Error(`Unsupported AssemblyPathLocation: ${descriptor.pathLocationType}`);
    }
  }

  /**
   * Adds or replaces an assembly entry in targets and libraries sections.
   * Uses a unified key format for all assemblies: `<name>/<version>` or `<name>/<version>__<token>`.
   */
  private addAssemblyEntry(
    targetSection: DepsJsonStructure['targets'][string],
    libraries: DepsJsonStructure['libraries'],
    descriptor: AssemblyDescriptor
  ): void {
    // Use unified key format: name/version or name/version__token
    const entryKey = this.buildDebsEntryName(descriptor);

    // Find and remove existing entries with similar name prefix
    const existingTargetKeys = Object.keys(targetSection).filter((key) =>
      key.startsWith(`${descriptor.name}/`)
    );
    for (const key of existingTargetKeys) {
      delete targetSection[key];
    }

    // Add to targets section
    targetSection[entryKey] = {
      runtime: {
        [descriptor.filePath]: {
          assemblyVersion: descriptor.assemblyVersion,
          fileVersion: descriptor.fileVersion,
        },
      },
    };

    const existingLibraryKeys = Object.keys(libraries).filter((key) =>
      key.startsWith(`${descriptor.name}/`)
    );
    for (const key of existingLibraryKeys) {
      delete libraries[key];
    }

    // Add to libraries section
    libraries[entryKey] = {
      type: 'package',
      serviceable: true,
      sha512: '',
      path: entryKey,
      hashPath: '',
    };
  }
}
