// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: native_bridge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NativeBridge {

  /// <summary>Holder for reflection information generated from native_bridge.proto</summary>
  public static partial class NativeBridgeReflection {

    #region Descriptor
    /// <summary>File descriptor for native_bridge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NativeBridgeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNuYXRpdmVfYnJpZGdlLnByb3RvEg1uYXRpdmVfYnJpZGdlIpQBCgpDbGlS",
            "ZXF1ZXN0EjwKDmNvbnRhY3RfZXhwb3J0GAogASgLMiIubmF0aXZlX2JyaWRn",
            "ZS5Db250YWN0RXhwb3J0UGFyYW1zSAASPgoPY2FsZW5kYXJfZXhwb3J0GAsg",
            "ASgLMiMubmF0aXZlX2JyaWRnZS5DYWxlbmRhckV4cG9ydFBhcmFtc0gAQggK",
            "BnBhcmFtcyIqChNDb250YWN0RXhwb3J0UGFyYW1zEhMKC2ZvbGRlcl9uYW1l",
            "GAEgASgJIm4KFENhbGVuZGFyRXhwb3J0UGFyYW1zEhIKCnN0YXJ0X2RhdGUY",
            "ASABKAMSEAoIZW5kX2RhdGUYAiABKAMSFwoPaW5jbHVkZV9wcml2YXRlGAMg",
            "ASgIEhcKD2NhbGVuZGFyX2ZvbGRlchgEIAEoCSKjAQoMRXhwb3J0UmVzdWx0",
            "Eg4KBGVjaG8YASABKAlIABIqCgZ2Y2FyZHMYAiABKAsyGC5uYXRpdmVfYnJp",
            "ZGdlLlZDYXJkRGF0YUgAEhcKDW1lcmdlZF92Y2FyZHMYAyABKAlIABIvCghj",
            "YWxlbmRhchgEIAEoCzIbLm5hdGl2ZV9icmlkZ2UuQ2FsZW5kYXJEYXRhSABC",
            "DQoLZXhwb3J0X2RhdGEiGwoJVkNhcmREYXRhEg4KBnZjYXJkcxgBIAMoCSIx",
            "CgxDYWxlbmRhckRhdGESDAoEaWNhbBgBIAEoCRITCgtldmVudF9jb3VudBgC",
            "IAEoBSK/AQoLQ2xpUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIVCg1lcnJv",
            "cl9tZXNzYWdlGAIgASgJEhkKEWVycm9yX3N0YWNrX3RyYWNlGAMgASgJEg8K",
            "B2NvbW1hbmQYBCABKAkSEQoJdGltZXN0YW1wGAUgASgDEjIKDWV4cG9ydF9y",
            "ZXN1bHQYCiABKAsyGy5uYXRpdmVfYnJpZGdlLkV4cG9ydFJlc3VsdBIVCg1z",
            "aW1wbGVfcmVzdWx0GBQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.CliRequest), global::NativeBridge.CliRequest.Parser, new[]{ "ContactExport", "CalendarExport" }, new[]{ "Params" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.ContactExportParams), global::NativeBridge.ContactExportParams.Parser, new[]{ "FolderName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.CalendarExportParams), global::NativeBridge.CalendarExportParams.Parser, new[]{ "StartDate", "EndDate", "IncludePrivate", "CalendarFolder" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.ExportResult), global::NativeBridge.ExportResult.Parser, new[]{ "Echo", "Vcards", "MergedVcards", "Calendar" }, new[]{ "ExportData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.VCardData), global::NativeBridge.VCardData.Parser, new[]{ "Vcards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.CalendarData), global::NativeBridge.CalendarData.Parser, new[]{ "Ical", "EventCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.CliResponse), global::NativeBridge.CliResponse.Parser, new[]{ "Success", "ErrorMessage", "ErrorStackTrace", "Command", "Timestamp", "ExportResult", "SimpleResult" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Unified request envelope sent via stdin.
  /// The command name is still passed as a CLI argument for discoverability;
  /// this message carries structured parameters for commands that need them.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CliRequest : pb::IMessage<CliRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CliRequest> _parser = new pb::MessageParser<CliRequest>(() => new CliRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CliRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliRequest(CliRequest other) : this() {
      switch (other.ParamsCase) {
        case ParamsOneofCase.ContactExport:
          ContactExport = other.ContactExport.Clone();
          break;
        case ParamsOneofCase.CalendarExport:
          CalendarExport = other.CalendarExport.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliRequest Clone() {
      return new CliRequest(this);
    }

    /// <summary>Field number for the "contact_export" field.</summary>
    public const int ContactExportFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.ContactExportParams ContactExport {
      get { return paramsCase_ == ParamsOneofCase.ContactExport ? (global::NativeBridge.ContactExportParams) params_ : null; }
      set {
        params_ = value;
        paramsCase_ = value == null ? ParamsOneofCase.None : ParamsOneofCase.ContactExport;
      }
    }

    /// <summary>Field number for the "calendar_export" field.</summary>
    public const int CalendarExportFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.CalendarExportParams CalendarExport {
      get { return paramsCase_ == ParamsOneofCase.CalendarExport ? (global::NativeBridge.CalendarExportParams) params_ : null; }
      set {
        params_ = value;
        paramsCase_ = value == null ? ParamsOneofCase.None : ParamsOneofCase.CalendarExport;
      }
    }

    private object params_;
    /// <summary>Enum of possible cases for the "params" oneof.</summary>
    public enum ParamsOneofCase {
      None = 0,
      ContactExport = 10,
      CalendarExport = 11,
    }
    private ParamsOneofCase paramsCase_ = ParamsOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParamsOneofCase ParamsCase {
      get { return paramsCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearParams() {
      paramsCase_ = ParamsOneofCase.None;
      params_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CliRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CliRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ContactExport, other.ContactExport)) return false;
      if (!object.Equals(CalendarExport, other.CalendarExport)) return false;
      if (ParamsCase != other.ParamsCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paramsCase_ == ParamsOneofCase.ContactExport) hash ^= ContactExport.GetHashCode();
      if (paramsCase_ == ParamsOneofCase.CalendarExport) hash ^= CalendarExport.GetHashCode();
      hash ^= (int) paramsCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paramsCase_ == ParamsOneofCase.ContactExport) {
        output.WriteRawTag(82);
        output.WriteMessage(ContactExport);
      }
      if (paramsCase_ == ParamsOneofCase.CalendarExport) {
        output.WriteRawTag(90);
        output.WriteMessage(CalendarExport);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paramsCase_ == ParamsOneofCase.ContactExport) {
        output.WriteRawTag(82);
        output.WriteMessage(ContactExport);
      }
      if (paramsCase_ == ParamsOneofCase.CalendarExport) {
        output.WriteRawTag(90);
        output.WriteMessage(CalendarExport);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paramsCase_ == ParamsOneofCase.ContactExport) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ContactExport);
      }
      if (paramsCase_ == ParamsOneofCase.CalendarExport) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CalendarExport);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CliRequest other) {
      if (other == null) {
        return;
      }
      switch (other.ParamsCase) {
        case ParamsOneofCase.ContactExport:
          if (ContactExport == null) {
            ContactExport = new global::NativeBridge.ContactExportParams();
          }
          ContactExport.MergeFrom(other.ContactExport);
          break;
        case ParamsOneofCase.CalendarExport:
          if (CalendarExport == null) {
            CalendarExport = new global::NativeBridge.CalendarExportParams();
          }
          CalendarExport.MergeFrom(other.CalendarExport);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 82: {
            global::NativeBridge.ContactExportParams subBuilder = new global::NativeBridge.ContactExportParams();
            if (paramsCase_ == ParamsOneofCase.ContactExport) {
              subBuilder.MergeFrom(ContactExport);
            }
            input.ReadMessage(subBuilder);
            ContactExport = subBuilder;
            break;
          }
          case 90: {
            global::NativeBridge.CalendarExportParams subBuilder = new global::NativeBridge.CalendarExportParams();
            if (paramsCase_ == ParamsOneofCase.CalendarExport) {
              subBuilder.MergeFrom(CalendarExport);
            }
            input.ReadMessage(subBuilder);
            CalendarExport = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 82: {
            global::NativeBridge.ContactExportParams subBuilder = new global::NativeBridge.ContactExportParams();
            if (paramsCase_ == ParamsOneofCase.ContactExport) {
              subBuilder.MergeFrom(ContactExport);
            }
            input.ReadMessage(subBuilder);
            ContactExport = subBuilder;
            break;
          }
          case 90: {
            global::NativeBridge.CalendarExportParams subBuilder = new global::NativeBridge.CalendarExportParams();
            if (paramsCase_ == ParamsOneofCase.CalendarExport) {
              subBuilder.MergeFrom(CalendarExport);
            }
            input.ReadMessage(subBuilder);
            CalendarExport = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Parameters for contact export command.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ContactExportParams : pb::IMessage<ContactExportParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ContactExportParams> _parser = new pb::MessageParser<ContactExportParams>(() => new ContactExportParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ContactExportParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContactExportParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContactExportParams(ContactExportParams other) : this() {
      folderName_ = other.folderName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContactExportParams Clone() {
      return new ContactExportParams(this);
    }

    /// <summary>Field number for the "folder_name" field.</summary>
    public const int FolderNameFieldNumber = 1;
    private string folderName_ = "";
    /// <summary>
    /// Optional: specific folder name to export from (empty = default contacts folder)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FolderName {
      get { return folderName_; }
      set {
        folderName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ContactExportParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ContactExportParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FolderName != other.FolderName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FolderName.Length != 0) hash ^= FolderName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FolderName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FolderName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FolderName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FolderName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FolderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FolderName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ContactExportParams other) {
      if (other == null) {
        return;
      }
      if (other.FolderName.Length != 0) {
        FolderName = other.FolderName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FolderName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FolderName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Parameters for calendar export command.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CalendarExportParams : pb::IMessage<CalendarExportParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CalendarExportParams> _parser = new pb::MessageParser<CalendarExportParams>(() => new CalendarExportParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CalendarExportParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarExportParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarExportParams(CalendarExportParams other) : this() {
      startDate_ = other.startDate_;
      endDate_ = other.endDate_;
      includePrivate_ = other.includePrivate_;
      calendarFolder_ = other.calendarFolder_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarExportParams Clone() {
      return new CalendarExportParams(this);
    }

    /// <summary>Field number for the "start_date" field.</summary>
    public const int StartDateFieldNumber = 1;
    private long startDate_;
    /// <summary>
    /// UTC ticks — start of export range
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StartDate {
      get { return startDate_; }
      set {
        startDate_ = value;
      }
    }

    /// <summary>Field number for the "end_date" field.</summary>
    public const int EndDateFieldNumber = 2;
    private long endDate_;
    /// <summary>
    /// UTC ticks — end of export range
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EndDate {
      get { return endDate_; }
      set {
        endDate_ = value;
      }
    }

    /// <summary>Field number for the "include_private" field.</summary>
    public const int IncludePrivateFieldNumber = 3;
    private bool includePrivate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IncludePrivate {
      get { return includePrivate_; }
      set {
        includePrivate_ = value;
      }
    }

    /// <summary>Field number for the "calendar_folder" field.</summary>
    public const int CalendarFolderFieldNumber = 4;
    private string calendarFolder_ = "";
    /// <summary>
    /// Optional: specific calendar folder name (empty = default calendar)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CalendarFolder {
      get { return calendarFolder_; }
      set {
        calendarFolder_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CalendarExportParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CalendarExportParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartDate != other.StartDate) return false;
      if (EndDate != other.EndDate) return false;
      if (IncludePrivate != other.IncludePrivate) return false;
      if (CalendarFolder != other.CalendarFolder) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StartDate != 0L) hash ^= StartDate.GetHashCode();
      if (EndDate != 0L) hash ^= EndDate.GetHashCode();
      if (IncludePrivate != false) hash ^= IncludePrivate.GetHashCode();
      if (CalendarFolder.Length != 0) hash ^= CalendarFolder.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StartDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StartDate);
      }
      if (EndDate != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(EndDate);
      }
      if (IncludePrivate != false) {
        output.WriteRawTag(24);
        output.WriteBool(IncludePrivate);
      }
      if (CalendarFolder.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CalendarFolder);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StartDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StartDate);
      }
      if (EndDate != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(EndDate);
      }
      if (IncludePrivate != false) {
        output.WriteRawTag(24);
        output.WriteBool(IncludePrivate);
      }
      if (CalendarFolder.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CalendarFolder);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StartDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartDate);
      }
      if (EndDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndDate);
      }
      if (IncludePrivate != false) {
        size += 1 + 1;
      }
      if (CalendarFolder.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CalendarFolder);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CalendarExportParams other) {
      if (other == null) {
        return;
      }
      if (other.StartDate != 0L) {
        StartDate = other.StartDate;
      }
      if (other.EndDate != 0L) {
        EndDate = other.EndDate;
      }
      if (other.IncludePrivate != false) {
        IncludePrivate = other.IncludePrivate;
      }
      if (other.CalendarFolder.Length != 0) {
        CalendarFolder = other.CalendarFolder;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartDate = input.ReadInt64();
            break;
          }
          case 16: {
            EndDate = input.ReadInt64();
            break;
          }
          case 24: {
            IncludePrivate = input.ReadBool();
            break;
          }
          case 34: {
            CalendarFolder = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StartDate = input.ReadInt64();
            break;
          }
          case 16: {
            EndDate = input.ReadInt64();
            break;
          }
          case 24: {
            IncludePrivate = input.ReadBool();
            break;
          }
          case 34: {
            CalendarFolder = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Export result containing vCard data
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExportResult : pb::IMessage<ExportResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExportResult> _parser = new pb::MessageParser<ExportResult>(() => new ExportResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExportResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult(ExportResult other) : this() {
      switch (other.ExportDataCase) {
        case ExportDataOneofCase.Echo:
          Echo = other.Echo;
          break;
        case ExportDataOneofCase.Vcards:
          Vcards = other.Vcards.Clone();
          break;
        case ExportDataOneofCase.MergedVcards:
          MergedVcards = other.MergedVcards;
          break;
        case ExportDataOneofCase.Calendar:
          Calendar = other.Calendar.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult Clone() {
      return new ExportResult(this);
    }

    /// <summary>Field number for the "echo" field.</summary>
    public const int EchoFieldNumber = 1;
    /// <summary>
    /// Echo test
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Echo {
      get { return HasEcho ? (string) exportData_ : ""; }
      set {
        exportData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        exportDataCase_ = ExportDataOneofCase.Echo;
      }
    }
    /// <summary>Gets whether the "echo" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEcho {
      get { return exportDataCase_ == ExportDataOneofCase.Echo; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "echo" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEcho() {
      if (HasEcho) {
        ClearExportData();
      }
    }

    /// <summary>Field number for the "vcards" field.</summary>
    public const int VcardsFieldNumber = 2;
    /// <summary>
    /// VCard Data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.VCardData Vcards {
      get { return exportDataCase_ == ExportDataOneofCase.Vcards ? (global::NativeBridge.VCardData) exportData_ : null; }
      set {
        exportData_ = value;
        exportDataCase_ = value == null ? ExportDataOneofCase.None : ExportDataOneofCase.Vcards;
      }
    }

    /// <summary>Field number for the "merged_vcards" field.</summary>
    public const int MergedVcardsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MergedVcards {
      get { return HasMergedVcards ? (string) exportData_ : ""; }
      set {
        exportData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        exportDataCase_ = ExportDataOneofCase.MergedVcards;
      }
    }
    /// <summary>Gets whether the "merged_vcards" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMergedVcards {
      get { return exportDataCase_ == ExportDataOneofCase.MergedVcards; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "merged_vcards" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMergedVcards() {
      if (HasMergedVcards) {
        ClearExportData();
      }
    }

    /// <summary>Field number for the "calendar" field.</summary>
    public const int CalendarFieldNumber = 4;
    /// <summary>
    /// iCalendar data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.CalendarData Calendar {
      get { return exportDataCase_ == ExportDataOneofCase.Calendar ? (global::NativeBridge.CalendarData) exportData_ : null; }
      set {
        exportData_ = value;
        exportDataCase_ = value == null ? ExportDataOneofCase.None : ExportDataOneofCase.Calendar;
      }
    }

    private object exportData_;
    /// <summary>Enum of possible cases for the "export_data" oneof.</summary>
    public enum ExportDataOneofCase {
      None = 0,
      Echo = 1,
      Vcards = 2,
      MergedVcards = 3,
      Calendar = 4,
    }
    private ExportDataOneofCase exportDataCase_ = ExportDataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportDataOneofCase ExportDataCase {
      get { return exportDataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExportData() {
      exportDataCase_ = ExportDataOneofCase.None;
      exportData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExportResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExportResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Echo != other.Echo) return false;
      if (!object.Equals(Vcards, other.Vcards)) return false;
      if (MergedVcards != other.MergedVcards) return false;
      if (!object.Equals(Calendar, other.Calendar)) return false;
      if (ExportDataCase != other.ExportDataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEcho) hash ^= Echo.GetHashCode();
      if (exportDataCase_ == ExportDataOneofCase.Vcards) hash ^= Vcards.GetHashCode();
      if (HasMergedVcards) hash ^= MergedVcards.GetHashCode();
      if (exportDataCase_ == ExportDataOneofCase.Calendar) hash ^= Calendar.GetHashCode();
      hash ^= (int) exportDataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEcho) {
        output.WriteRawTag(10);
        output.WriteString(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        output.WriteRawTag(18);
        output.WriteMessage(Vcards);
      }
      if (HasMergedVcards) {
        output.WriteRawTag(26);
        output.WriteString(MergedVcards);
      }
      if (exportDataCase_ == ExportDataOneofCase.Calendar) {
        output.WriteRawTag(34);
        output.WriteMessage(Calendar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEcho) {
        output.WriteRawTag(10);
        output.WriteString(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        output.WriteRawTag(18);
        output.WriteMessage(Vcards);
      }
      if (HasMergedVcards) {
        output.WriteRawTag(26);
        output.WriteString(MergedVcards);
      }
      if (exportDataCase_ == ExportDataOneofCase.Calendar) {
        output.WriteRawTag(34);
        output.WriteMessage(Calendar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEcho) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vcards);
      }
      if (HasMergedVcards) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MergedVcards);
      }
      if (exportDataCase_ == ExportDataOneofCase.Calendar) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Calendar);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExportResult other) {
      if (other == null) {
        return;
      }
      switch (other.ExportDataCase) {
        case ExportDataOneofCase.Echo:
          Echo = other.Echo;
          break;
        case ExportDataOneofCase.Vcards:
          if (Vcards == null) {
            Vcards = new global::NativeBridge.VCardData();
          }
          Vcards.MergeFrom(other.Vcards);
          break;
        case ExportDataOneofCase.MergedVcards:
          MergedVcards = other.MergedVcards;
          break;
        case ExportDataOneofCase.Calendar:
          if (Calendar == null) {
            Calendar = new global::NativeBridge.CalendarData();
          }
          Calendar.MergeFrom(other.Calendar);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Echo = input.ReadString();
            break;
          }
          case 18: {
            global::NativeBridge.VCardData subBuilder = new global::NativeBridge.VCardData();
            if (exportDataCase_ == ExportDataOneofCase.Vcards) {
              subBuilder.MergeFrom(Vcards);
            }
            input.ReadMessage(subBuilder);
            Vcards = subBuilder;
            break;
          }
          case 26: {
            MergedVcards = input.ReadString();
            break;
          }
          case 34: {
            global::NativeBridge.CalendarData subBuilder = new global::NativeBridge.CalendarData();
            if (exportDataCase_ == ExportDataOneofCase.Calendar) {
              subBuilder.MergeFrom(Calendar);
            }
            input.ReadMessage(subBuilder);
            Calendar = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Echo = input.ReadString();
            break;
          }
          case 18: {
            global::NativeBridge.VCardData subBuilder = new global::NativeBridge.VCardData();
            if (exportDataCase_ == ExportDataOneofCase.Vcards) {
              subBuilder.MergeFrom(Vcards);
            }
            input.ReadMessage(subBuilder);
            Vcards = subBuilder;
            break;
          }
          case 26: {
            MergedVcards = input.ReadString();
            break;
          }
          case 34: {
            global::NativeBridge.CalendarData subBuilder = new global::NativeBridge.CalendarData();
            if (exportDataCase_ == ExportDataOneofCase.Calendar) {
              subBuilder.MergeFrom(Calendar);
            }
            input.ReadMessage(subBuilder);
            Calendar = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VCardData : pb::IMessage<VCardData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VCardData> _parser = new pb::MessageParser<VCardData>(() => new VCardData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VCardData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData(VCardData other) : this() {
      vcards_ = other.vcards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData Clone() {
      return new VCardData(this);
    }

    /// <summary>Field number for the "vcards" field.</summary>
    public const int VcardsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_vcards_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> vcards_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of vCards generated by some backend
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Vcards {
      get { return vcards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VCardData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VCardData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!vcards_.Equals(other.vcards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= vcards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      vcards_.WriteTo(output, _repeated_vcards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      vcards_.WriteTo(ref output, _repeated_vcards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += vcards_.CalculateSize(_repeated_vcards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VCardData other) {
      if (other == null) {
        return;
      }
      vcards_.Add(other.vcards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            vcards_.AddEntriesFrom(input, _repeated_vcards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            vcards_.AddEntriesFrom(ref input, _repeated_vcards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Calendar export result containing iCalendar event data
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CalendarData : pb::IMessage<CalendarData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CalendarData> _parser = new pb::MessageParser<CalendarData>(() => new CalendarData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CalendarData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarData(CalendarData other) : this() {
      ical_ = other.ical_;
      eventCount_ = other.eventCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CalendarData Clone() {
      return new CalendarData(this);
    }

    /// <summary>Field number for the "ical" field.</summary>
    public const int IcalFieldNumber = 1;
    private string ical_ = "";
    /// <summary>
    /// Full iCalendar string (VCALENDAR with VEVENT components)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ical {
      get { return ical_; }
      set {
        ical_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "event_count" field.</summary>
    public const int EventCountFieldNumber = 2;
    private int eventCount_;
    /// <summary>
    /// Number of events in the export
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventCount {
      get { return eventCount_; }
      set {
        eventCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CalendarData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CalendarData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ical != other.Ical) return false;
      if (EventCount != other.EventCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ical.Length != 0) hash ^= Ical.GetHashCode();
      if (EventCount != 0) hash ^= EventCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ical.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ical);
      }
      if (EventCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ical.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Ical);
      }
      if (EventCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ical.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ical);
      }
      if (EventCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CalendarData other) {
      if (other == null) {
        return;
      }
      if (other.Ical.Length != 0) {
        Ical = other.Ical;
      }
      if (other.EventCount != 0) {
        EventCount = other.EventCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Ical = input.ReadString();
            break;
          }
          case 16: {
            EventCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Ical = input.ReadString();
            break;
          }
          case 16: {
            EventCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CLI response wrapper
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CliResponse : pb::IMessage<CliResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CliResponse> _parser = new pb::MessageParser<CliResponse>(() => new CliResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CliResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse(CliResponse other) : this() {
      success_ = other.success_;
      errorMessage_ = other.errorMessage_;
      errorStackTrace_ = other.errorStackTrace_;
      command_ = other.command_;
      timestamp_ = other.timestamp_;
      exportResult_ = other.exportResult_ != null ? other.exportResult_.Clone() : null;
      simpleResult_ = other.simpleResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse Clone() {
      return new CliResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 2;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error_stack_trace" field.</summary>
    public const int ErrorStackTraceFieldNumber = 3;
    private string errorStackTrace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorStackTrace {
      get { return errorStackTrace_; }
      set {
        errorStackTrace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 4;
    private string command_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Command {
      get { return command_; }
      set {
        command_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private long timestamp_;
    /// <summary>
    /// UTC ticks
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "export_result" field.</summary>
    public const int ExportResultFieldNumber = 10;
    private global::NativeBridge.ExportResult exportResult_;
    /// <summary>
    /// Export result when command returns data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.ExportResult ExportResult {
      get { return exportResult_; }
      set {
        exportResult_ = value;
      }
    }

    /// <summary>Field number for the "simple_result" field.</summary>
    public const int SimpleResultFieldNumber = 20;
    private string simpleResult_ = "";
    /// <summary>
    /// Simple string result for commands like ping, list-commands
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SimpleResult {
      get { return simpleResult_; }
      set {
        simpleResult_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CliResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CliResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (ErrorStackTrace != other.ErrorStackTrace) return false;
      if (Command != other.Command) return false;
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(ExportResult, other.ExportResult)) return false;
      if (SimpleResult != other.SimpleResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (ErrorStackTrace.Length != 0) hash ^= ErrorStackTrace.GetHashCode();
      if (Command.Length != 0) hash ^= Command.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (exportResult_ != null) hash ^= ExportResult.GetHashCode();
      if (SimpleResult.Length != 0) hash ^= SimpleResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Command);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (exportResult_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(SimpleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Command);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (exportResult_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(SimpleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Command);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (exportResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SimpleResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CliResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      if (other.ErrorStackTrace.Length != 0) {
        ErrorStackTrace = other.ErrorStackTrace;
      }
      if (other.Command.Length != 0) {
        Command = other.Command;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.exportResult_ != null) {
        if (exportResult_ == null) {
          ExportResult = new global::NativeBridge.ExportResult();
        }
        ExportResult.MergeFrom(other.ExportResult);
      }
      if (other.SimpleResult.Length != 0) {
        SimpleResult = other.SimpleResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            ErrorStackTrace = input.ReadString();
            break;
          }
          case 34: {
            Command = input.ReadString();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 82: {
            if (exportResult_ == null) {
              ExportResult = new global::NativeBridge.ExportResult();
            }
            input.ReadMessage(ExportResult);
            break;
          }
          case 162: {
            SimpleResult = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            ErrorStackTrace = input.ReadString();
            break;
          }
          case 34: {
            Command = input.ReadString();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 82: {
            if (exportResult_ == null) {
              ExportResult = new global::NativeBridge.ExportResult();
            }
            input.ReadMessage(ExportResult);
            break;
          }
          case 162: {
            SimpleResult = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
