// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: native_bridge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NativeBridge {

  /// <summary>Holder for reflection information generated from native_bridge.proto</summary>
  public static partial class NativeBridgeReflection {

    #region Descriptor
    /// <summary>File descriptor for native_bridge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NativeBridgeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNuYXRpdmVfYnJpZGdlLnByb3RvEg1uYXRpdmVfYnJpZGdlInIKDEV4cG9y",
            "dFJlc3VsdBIOCgRlY2hvGAEgASgJSAASKgoGdmNhcmRzGAIgASgLMhgubmF0",
            "aXZlX2JyaWRnZS5WQ2FyZERhdGFIABIXCg1tZXJnZWRfdmNhcmRzGAMgASgJ",
            "SABCDQoLZXhwb3J0X2RhdGEiGwoJVkNhcmREYXRhEg4KBnZjYXJkcxgBIAMo",
            "CSK/AQoLQ2xpUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIVCg1lcnJvcl9t",
            "ZXNzYWdlGAIgASgJEhkKEWVycm9yX3N0YWNrX3RyYWNlGAMgASgJEg8KB2Nv",
            "bW1hbmQYBCABKAkSEQoJdGltZXN0YW1wGAUgASgDEjIKDWV4cG9ydF9yZXN1",
            "bHQYCiABKAsyGy5uYXRpdmVfYnJpZGdlLkV4cG9ydFJlc3VsdBIVCg1zaW1w",
            "bGVfcmVzdWx0GBQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.ExportResult), global::NativeBridge.ExportResult.Parser, new[]{ "Echo", "Vcards", "MergedVcards" }, new[]{ "ExportData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.VCardData), global::NativeBridge.VCardData.Parser, new[]{ "Vcards" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NativeBridge.CliResponse), global::NativeBridge.CliResponse.Parser, new[]{ "Success", "ErrorMessage", "ErrorStackTrace", "Command", "Timestamp", "ExportResult", "SimpleResult" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Export result containing vCard data
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExportResult : pb::IMessage<ExportResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExportResult> _parser = new pb::MessageParser<ExportResult>(() => new ExportResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExportResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult(ExportResult other) : this() {
      switch (other.ExportDataCase) {
        case ExportDataOneofCase.Echo:
          Echo = other.Echo;
          break;
        case ExportDataOneofCase.Vcards:
          Vcards = other.Vcards.Clone();
          break;
        case ExportDataOneofCase.MergedVcards:
          MergedVcards = other.MergedVcards;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportResult Clone() {
      return new ExportResult(this);
    }

    /// <summary>Field number for the "echo" field.</summary>
    public const int EchoFieldNumber = 1;
    /// <summary>
    /// Echo test
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Echo {
      get { return HasEcho ? (string) exportData_ : ""; }
      set {
        exportData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        exportDataCase_ = ExportDataOneofCase.Echo;
      }
    }
    /// <summary>Gets whether the "echo" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEcho {
      get { return exportDataCase_ == ExportDataOneofCase.Echo; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "echo" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEcho() {
      if (HasEcho) {
        ClearExportData();
      }
    }

    /// <summary>Field number for the "vcards" field.</summary>
    public const int VcardsFieldNumber = 2;
    /// <summary>
    /// VCard Data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.VCardData Vcards {
      get { return exportDataCase_ == ExportDataOneofCase.Vcards ? (global::NativeBridge.VCardData) exportData_ : null; }
      set {
        exportData_ = value;
        exportDataCase_ = value == null ? ExportDataOneofCase.None : ExportDataOneofCase.Vcards;
      }
    }

    /// <summary>Field number for the "merged_vcards" field.</summary>
    public const int MergedVcardsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MergedVcards {
      get { return HasMergedVcards ? (string) exportData_ : ""; }
      set {
        exportData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        exportDataCase_ = ExportDataOneofCase.MergedVcards;
      }
    }
    /// <summary>Gets whether the "merged_vcards" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMergedVcards {
      get { return exportDataCase_ == ExportDataOneofCase.MergedVcards; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "merged_vcards" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMergedVcards() {
      if (HasMergedVcards) {
        ClearExportData();
      }
    }

    private object exportData_;
    /// <summary>Enum of possible cases for the "export_data" oneof.</summary>
    public enum ExportDataOneofCase {
      None = 0,
      Echo = 1,
      Vcards = 2,
      MergedVcards = 3,
    }
    private ExportDataOneofCase exportDataCase_ = ExportDataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExportDataOneofCase ExportDataCase {
      get { return exportDataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExportData() {
      exportDataCase_ = ExportDataOneofCase.None;
      exportData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExportResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExportResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Echo != other.Echo) return false;
      if (!object.Equals(Vcards, other.Vcards)) return false;
      if (MergedVcards != other.MergedVcards) return false;
      if (ExportDataCase != other.ExportDataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEcho) hash ^= Echo.GetHashCode();
      if (exportDataCase_ == ExportDataOneofCase.Vcards) hash ^= Vcards.GetHashCode();
      if (HasMergedVcards) hash ^= MergedVcards.GetHashCode();
      hash ^= (int) exportDataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEcho) {
        output.WriteRawTag(10);
        output.WriteString(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        output.WriteRawTag(18);
        output.WriteMessage(Vcards);
      }
      if (HasMergedVcards) {
        output.WriteRawTag(26);
        output.WriteString(MergedVcards);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEcho) {
        output.WriteRawTag(10);
        output.WriteString(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        output.WriteRawTag(18);
        output.WriteMessage(Vcards);
      }
      if (HasMergedVcards) {
        output.WriteRawTag(26);
        output.WriteString(MergedVcards);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEcho) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Echo);
      }
      if (exportDataCase_ == ExportDataOneofCase.Vcards) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Vcards);
      }
      if (HasMergedVcards) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MergedVcards);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExportResult other) {
      if (other == null) {
        return;
      }
      switch (other.ExportDataCase) {
        case ExportDataOneofCase.Echo:
          Echo = other.Echo;
          break;
        case ExportDataOneofCase.Vcards:
          if (Vcards == null) {
            Vcards = new global::NativeBridge.VCardData();
          }
          Vcards.MergeFrom(other.Vcards);
          break;
        case ExportDataOneofCase.MergedVcards:
          MergedVcards = other.MergedVcards;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Echo = input.ReadString();
            break;
          }
          case 18: {
            global::NativeBridge.VCardData subBuilder = new global::NativeBridge.VCardData();
            if (exportDataCase_ == ExportDataOneofCase.Vcards) {
              subBuilder.MergeFrom(Vcards);
            }
            input.ReadMessage(subBuilder);
            Vcards = subBuilder;
            break;
          }
          case 26: {
            MergedVcards = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Echo = input.ReadString();
            break;
          }
          case 18: {
            global::NativeBridge.VCardData subBuilder = new global::NativeBridge.VCardData();
            if (exportDataCase_ == ExportDataOneofCase.Vcards) {
              subBuilder.MergeFrom(Vcards);
            }
            input.ReadMessage(subBuilder);
            Vcards = subBuilder;
            break;
          }
          case 26: {
            MergedVcards = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VCardData : pb::IMessage<VCardData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VCardData> _parser = new pb::MessageParser<VCardData>(() => new VCardData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VCardData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData(VCardData other) : this() {
      vcards_ = other.vcards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VCardData Clone() {
      return new VCardData(this);
    }

    /// <summary>Field number for the "vcards" field.</summary>
    public const int VcardsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_vcards_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> vcards_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of vCards generated by some backend
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Vcards {
      get { return vcards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VCardData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VCardData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!vcards_.Equals(other.vcards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= vcards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      vcards_.WriteTo(output, _repeated_vcards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      vcards_.WriteTo(ref output, _repeated_vcards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += vcards_.CalculateSize(_repeated_vcards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VCardData other) {
      if (other == null) {
        return;
      }
      vcards_.Add(other.vcards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            vcards_.AddEntriesFrom(input, _repeated_vcards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            vcards_.AddEntriesFrom(ref input, _repeated_vcards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// CLI response wrapper
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CliResponse : pb::IMessage<CliResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CliResponse> _parser = new pb::MessageParser<CliResponse>(() => new CliResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CliResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NativeBridge.NativeBridgeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse(CliResponse other) : this() {
      success_ = other.success_;
      errorMessage_ = other.errorMessage_;
      errorStackTrace_ = other.errorStackTrace_;
      command_ = other.command_;
      timestamp_ = other.timestamp_;
      exportResult_ = other.exportResult_ != null ? other.exportResult_.Clone() : null;
      simpleResult_ = other.simpleResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CliResponse Clone() {
      return new CliResponse(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 2;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error_stack_trace" field.</summary>
    public const int ErrorStackTraceFieldNumber = 3;
    private string errorStackTrace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorStackTrace {
      get { return errorStackTrace_; }
      set {
        errorStackTrace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 4;
    private string command_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Command {
      get { return command_; }
      set {
        command_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private long timestamp_;
    /// <summary>
    /// UTC ticks
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "export_result" field.</summary>
    public const int ExportResultFieldNumber = 10;
    private global::NativeBridge.ExportResult exportResult_;
    /// <summary>
    /// Export result when command returns data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NativeBridge.ExportResult ExportResult {
      get { return exportResult_; }
      set {
        exportResult_ = value;
      }
    }

    /// <summary>Field number for the "simple_result" field.</summary>
    public const int SimpleResultFieldNumber = 20;
    private string simpleResult_ = "";
    /// <summary>
    /// Simple string result for commands like ping, list-commands
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SimpleResult {
      get { return simpleResult_; }
      set {
        simpleResult_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CliResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CliResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      if (ErrorStackTrace != other.ErrorStackTrace) return false;
      if (Command != other.Command) return false;
      if (Timestamp != other.Timestamp) return false;
      if (!object.Equals(ExportResult, other.ExportResult)) return false;
      if (SimpleResult != other.SimpleResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (ErrorStackTrace.Length != 0) hash ^= ErrorStackTrace.GetHashCode();
      if (Command.Length != 0) hash ^= Command.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (exportResult_ != null) hash ^= ExportResult.GetHashCode();
      if (SimpleResult.Length != 0) hash ^= SimpleResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Command);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (exportResult_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(SimpleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Command);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (exportResult_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(SimpleResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (ErrorStackTrace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorStackTrace);
      }
      if (Command.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Command);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (exportResult_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExportResult);
      }
      if (SimpleResult.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SimpleResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CliResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      if (other.ErrorStackTrace.Length != 0) {
        ErrorStackTrace = other.ErrorStackTrace;
      }
      if (other.Command.Length != 0) {
        Command = other.Command;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.exportResult_ != null) {
        if (exportResult_ == null) {
          ExportResult = new global::NativeBridge.ExportResult();
        }
        ExportResult.MergeFrom(other.ExportResult);
      }
      if (other.SimpleResult.Length != 0) {
        SimpleResult = other.SimpleResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            ErrorStackTrace = input.ReadString();
            break;
          }
          case 34: {
            Command = input.ReadString();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 82: {
            if (exportResult_ == null) {
              ExportResult = new global::NativeBridge.ExportResult();
            }
            input.ReadMessage(ExportResult);
            break;
          }
          case 162: {
            SimpleResult = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            ErrorMessage = input.ReadString();
            break;
          }
          case 26: {
            ErrorStackTrace = input.ReadString();
            break;
          }
          case 34: {
            Command = input.ReadString();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 82: {
            if (exportResult_ == null) {
              ExportResult = new global::NativeBridge.ExportResult();
            }
            input.ReadMessage(ExportResult);
            break;
          }
          case 162: {
            SimpleResult = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
