/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Patch path.resolve to redirect electron-edge-js native module resolution to plugin directory
(function () {
  const originalResolve = require('path').resolve;
  const pluginDir = global.__OBSIDIAN_PLUGIN_DIR__;
  let isPatching = false; // Prevent recursion

  require('path').resolve = function (...args) {
    if (isPatching) {
      return originalResolve.apply(this, args);
    }

    isPatching = true;
    try {
      const result = originalResolve.apply(this, args);

      // Intercept edge-js, electron-edge-js and edge-cs native path resolution
      // Check for native module paths that need redirection
      const isElectronEdgeJs = result.includes('electron-edge-js');
      const isEdgeCs = result.includes('edge-cs');
      const isEdgeJs = !isElectronEdgeJs && result.includes('edge-js');

      if (
        pluginDir &&
        (isElectronEdgeJs || isEdgeCs || isEdgeJs) &&
        result.includes('lib') &&
        result.includes('native')
      ) {
        // Extract the relative native path from the original result
        const match = result.match(/native[\\/](.+)$/);
        if (match) {
          const nativeSuffix = match[1];
          // Determine which module based on the original path
          let moduleName;
          if (isElectronEdgeJs) {
            moduleName = 'electron-edge-js';
          } else if (isEdgeCs) {
            moduleName = 'edge-cs';
          } else {
            moduleName = 'edge-js';
          }
          const pluginNativePath = originalResolve(
            pluginDir,
            'outlookcombridge',
            moduleName,
            'lib',
            'native',
            nativeSuffix
          );
          console.log('[path.resolve patch] Redirecting:', result, '->', pluginNativePath);
          return pluginNativePath;
        }
      }

      return result;
    } finally {
      isPatching = false;
    }
  };
})();
